/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useState, useMemo } from 'react'
import { useThree } from '@react-three/fiber'
import { useGLTF, Float } from '@react-three/drei'
import { LayerMaterial, Color, Depth, Fresnel, Noise } from 'lamina/vanilla'

const colorA = new THREE.Color('#2032A5').convertSRGBToLinear()
const colorB = new THREE.Color('#0F1C4D').convertSRGBToLinear()
const fresnel = new THREE.Color('#E7B473').convertSRGBToLinear()
const material = new LayerMaterial({
  layers: [
    new Color({ color: colorA }),
    new Depth({ colorA: colorA, colorB: colorB, alpha: 0.5, mode: 'normal', near: 0, far: 2, origin: [1, 1, 1] }),
    new Depth({ colorA: 'purple', colorB: colorB, alpha: 0.5, mode: 'add', near: 3, far: 2, origin: [1, 1, 1] }),
    new Fresnel({ mode: 'add', color: fresnel, intensity: 0.3, power: 2.5, bias: 0.0 }),
    new Noise({ mapping: 'local', type: 'simplex', scale: 1000, colorA: '#ffaf40', colorB: 'black', mode: 'overlay' })
  ]
})

function Noodle({glb}) {
  const { viewport, camera } = useThree()
  let glbs = '/worms-transformed.glb';
  if (glb) {glbs = glb};
  const { nodes } = useGLTF(glbs)
  //alert(glb)
  // const [geometry] = useState(() => nodes[`noodle_${Math.ceil(Math.random() * 4)}_Ethereum_logo_@akimovcg${() =>{
  //   if (Math.ceil(Math.random() * 4) !== 1) {return '.00' + Math.ceil(Math.random() * 4)}
  // }
  // }`].geometry)
  const [geometry] = useState(() => nodes[`noodle_${Math.ceil(Math.random() * 4)}`].geometry)
  const [speed] = useState(() => 0.1 + Math.random() / 10)
  const position = useMemo(() => {
    const z = Math.random() * -30
    const bounds = viewport.getCurrentViewport(camera, [0, 0, -20])
    return [THREE.MathUtils.randFloatSpread(bounds.width), THREE.MathUtils.randFloatSpread(bounds.height * 0.75), z]
  }, [viewport])
  return (
    <Float position={position} speed={speed} rotationIntensity={10} floatIntensity={40} dispose={null}>
      <mesh scale={8} geometry={geometry} material={material} />
    </Float>
  )
}

export default function FloatingObjects({glb}) {
  return Array.from({ length: 25 }, (_, i) => <Noodle key={i} glb={glb} />)
}

useGLTF.preload('/worms-transformed.glb')
//useGLTF.preload('/ether_scene_no_box.glb')
